FROM fedora:20
MAINTAINER "Punit Porwal"

RUN yum -y update && yum clean all
RUN yum -y install httpd && yum clean all
RUN echo "<a href="https://cloudnetes.blogspot.com"><span title="cloudnetes">
    <img border='0' src="https://img.icons8.com/color/48/000000/money-heist-dali.png"/></span></a>" >> /var/www/html/index.html \
    echo "Apache Instance 1.0 to test ECS on AWS" >> /var/www/html/index.html
    
EXPOSE 80

ADD run.sh /run.sh
RUN chmod -v +x /run.sh
CMD ["/run.sh"]
  
#!/bin/bash

rm -rf /run/httpd/*
exec /usr/sbin/apachectl -D FOREGROUND
